### ISSUE TITLE
problem about example fitnessmachine with human

### ISSUE THREAD

**Issue by longbinzhang** [AnyBody/anybody-tutorial#73]
Hi, when I run the tutorial of 14. making models using solidworks.  The mannequin.any file of the model you given is not right. there is an error, "ERROR(SCR.PRS9) :   C:/P..s/A..y/A..1/AMMR/Body/A..n/T..k/InitialPositions.any(65)  :   'NeckRotation'  :  Unresolved object".
 I found this is that the mannequin.any file you given,  you delete,  AnyVar NeckLateralBending=0;   AnyVar NeckRotation=0;  After adding these, it works. 
What I did is right, right?

**Comment by melund** [comment]
Thank you so much for spotting this error @longbinzhang, and taking your time to report it. You fix is absolutely right. The values were missing.

I have put in a fix in #74. A preview of the fix should be live on the development version of the tutorials here soon: https://anyscript.org/tutorials/dev/
