### ISSUE TITLE
How to modify Squat model to Stoop model

### ISSUE THREAD

**Issue by hanghoo** [AnyBody/anybody-tutorial#88]
I want to use stoop model, but I only see squat model in AMMRs. So I need to change the file RightLegTLEMDrivers.any, right? And how could I modify the code?

**Comment by melund** [comment]
Hi @Hoototo. This is the wrong place to ask questions like this. Use http://forum.anscript.org for questions etc. ( we just launched a new system which is much nicer).

You can use the squatting model as a starting point for a model. There is a possibility, that you can get access to the beta version of the AMMR. It has some new standing model examples which are really good starting points when making new models.
