### ISSUE TITLE
Unable to load OptimBike2-final model from Optimization Studies tutorial

### ISSUE THREAD

**Issue by omarel-edrissi** [AnyBody/anybody-tutorial#92]
If you try to load the OptimBike2-final model from the Optimization Studies tutorial the following error message occurs:

Loading Settings Script from : 'C:\Users\omar\AppData\Local\AnyBody Technology\AnyBody.7.2.x\Settings.anyst
Settings Loaded
Loading  Main  :  "D:\USERNAME\Downloads\OptimBike2-final(1)\OptimBike2\BikeModel2D.main.any"
Scanning...
Parsing...
Constructing model tree...
ERROR(SCR.PRS2) :   D:/USERNAME/D..s/O..)/Op..e2/BikeModel2D.main.any(86)  :   'Pmet'  :  Object already auto declared by owner  :  Main.Study
Model loading skipped

AnyBody Tutorial Version 7.2.1
AnyBody Version 7.2.1 6927

Tutorial link:
https://anyscript.org/tutorials/dev/Parameter_studies_and_optimization/lesson2.html
Model download link: 
https://anyscript.org/tutorials/dev/_downloads/27ef9f3fe8e2181855afd217b10f4cee/OptimBike2-final.zip

**Comment by omarel-edrissi** [comment]
If you try to load the OptimBike2-final model from the Optimization Studies tutorial the following error message occurs:

Loading Settings Script from : 'C:\Users\omar\AppData\Local\AnyBody Technology\AnyBody.7.2.x\Settings.anyst
Settings Loaded
Loading  Main  :  "D:\USERNAME\Downloads\OptimBike2-final(1)\OptimBike2\BikeModel2D.main.any"
Scanning...
Parsing...
Constructing model tree...
ERROR(SCR.PRS2) :   D:/USERNAME/D..s/O..)/Op..e2/BikeModel2D.main.any(86)  :   'Pmet'  :  Object already auto declared by owner  :  Main.Study
Model loading skipped

AnyBody Tutorial Version 7.2.1
AnyBody Version 7.2.1 6927

Tutorial link:
https://anyscript.org/tutorials/dev/Parameter_studies_and_optimization/lesson2.html
Model download link: 
https://anyscript.org/tutorials/dev/_downloads/27ef9f3fe8e2181855afd217b10f4cee/OptimBike2-final.zip

**Comment by melund** [comment]
Thanks a ton for reporting this @omarel-edrissi. It seems the latest version of AnyBody may  have introduced a new built-in member which clashed with a variable name used in that tutorial. That is my guess anyway until I get a chance to look at it and fix it later. 

Maybe you can rename the variable as a workaround. Again. That a lot for talking your time reporting it :)
