### ISSUE TITLE
Graphs not matching output

### ISSUE THREAD

**Issue by mhtwedt** [AnyBody/anybody-tutorial#96]
Hi,

I'm only a couple lessons through the tutorial, but I've found some discrepancies between the data reported in the tutorial, and the data outputted by the program. I'm partly wondering if I'm doing something wrong, but nearly every plot I've compared my data with has been wrong. As an example, here is a comparison in section 3, lesson 4. This is the plot of the spring w/o any spring constant. This model was taken from the completed model downloaded at the end of the lesson.

![image](https://user-images.githubusercontent.com/28916151/66787482-75845000-eea9-11e9-8b92-41f076e928c1.png)

Compared to the graph in the tutorial

![image](https://user-images.githubusercontent.com/28916151/66787597-e6c40300-eea9-11e9-824f-2752854fd0a6.png)

Perhaps I am doing something wrong.
Let me know,

Max

**Comment by cdzialo** [comment]
Hi Max,

I just went in and ran the model and obtained the same results as you.  Originally when the tutorials were created a different version of the AMMR was being used.  We are currently going back and reworking the tutorials to take into account these changes.  Thank you for drawing our attention to this one.  


![image](https://user-images.githubusercontent.com/35573452/67090698-0eb5ae00-f1ab-11e9-984c-60b44cd964b6.png)

and the second plot will now be this:

![image](https://user-images.githubusercontent.com/35573452/67090951-9dc2c600-f1ab-11e9-9128-f547958a167a.png)


Hope this helps.


Best Regards,
Christine

**Comment by mhtwedt** [comment]
Hey Christine,

That is excellent, and the answer I was hoping for. I suppose there is no rush to fix the graphs, and if you would like me to keep track of which graphs have different results I can do that.

I have an unrelated question about a demo that I will find a place for.

Cheers,
Max

**Comment by cdzialo** [comment]
Hi Max,

That would be very useful actually thank you.

Best Regards,
Christine
